johnktravers/gut_savvy_ui

- .travis.yml
- app/controllers/welcome_controller.rb
- app/views/layouts/application.html.erb
- app/views/welcome/index.html.erb
- config/routes.rb
- spec/features/welcome_spec.rb
- Create test to verify view of welcome page
- Create root route for welcome page
- Create Welcome Controller and index method
- Create view for welcome page
- Create nav bar in application layout view
- Test coverage is 100%
> Welcome Page

- app/controllers/help_controller.rb
- app/views/help/show.html.erb
- config/routes.rb
- spec/features/help_page_spec.rb
- Add help page, currently uses place holder text for features that aren't built
> Help page rh

- app/views/help/show.html.erb
- app/views/layouts/application.html.erb
- app/views/meals/new.html.erb
- app/views/results/index.html.erb
- app/views/users/new.html.erb
- app/views/users/show.html.erb
- app/views/welcome/index.html.erb
- Add bootstrap stylesheet and javascript files
- Add margins, text centering, and button styling to all existing pages
- 100% test coverage
> Add Bootstrap Styling

- app/controllers/sessions_controller.rb
- app/views/layouts/application.html.erb
- app/views/users/new.html.erb
- config/routes.rb
- spec/features/users/google_oauth_spec.rb
- spec/features/welcome_spec.rb
- Add tests for log in and log out functionality for a user
- Condense register and login routes to be a single sign in route
- Update nav bar to show sign in link instead of register and login
- Update Sessions controller create method to check for user in database before creating a new user
> Log in and log out functionality 

- app/controllers/application_controller.rb
- app/controllers/dishes_controller.rb
- app/controllers/foods_controller.rb
- app/controllers/meals_controller.rb
- app/controllers/users_controller.rb
- app/models/dish.rb
- app/models/food.rb
- app/models/meal.rb
- app/models/user.rb
- app/services/fdc_service.rb
- app/views/dishes/new.html.erb
- app/views/foods/new.html.erb
- app/views/meals/new.html.erb
- config/routes.rb
- spec/factories/foods.rb
- spec/features/dashboard_spec.rb
- spec/features/users/google_oauth_spec.rb
- spec/features/users/user_adds_meal_spec.rb
- spec/models/dish_spec.rb
- spec/models/food_spec.rb
- spec/models/meal_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
- Add functionality for user to add food by upc code
- Add functionality for user to build dishes out of foods
- Add functionality for user to build meals out of dishes
- Add functionality for user to log meals to their account
- Meals no longer validate the presence of a gut feeling, since they will be added later by the user
- Any user specific page now requires a visitor to log in
> Meal entry

- app/controllers/foods_controller.rb
- app/controllers/sessions/dishes_controller.rb
- app/views/dishes/new.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- spec/features/users/user_adds_meal_spec.rb
- spec/features/users/user_adds_previous_foods_to_dishes_spec.rb
- spec/features/users/user_deletes_food_from_dish_spec.rb
- Add functionality for user to add previously used foods in the creation of a new dish
- Add functionality for user to delete foods from a new dish before dish creation
- Format table of previously used foods using DataTables jQuery plugin to include pagination, sorting, and search functionality
- Fix bug that user can enter a blank UPC code
- Test coverage is at 100%
> User can add previous foods

- app/controllers/sessions/meals_controller.rb
- app/views/meals/new.html.erb
- config/routes.rb
- spec/features/users/can_add_previous_dishes_to_meals_spec.rb
- User can now select previously used dishes and reuse them in a new meal
> Add previous dishes

- app/controllers/meals_controller.rb
- app/models/dish.rb
- app/views/dishes/new.html.erb
- app/views/layouts/application.html.erb
- app/views/meals/edit.html.erb
- app/views/meals/new.html.erb
- spec/features/users/user_edits_meal_spec.rb
- spec/models/dish_spec.rb
-Add Results link to nav bar
-Remove validations for uniqueness of name for Dish
-Gut feeling is not set to be -5 to 5 with no input field
-Previous foods and dish names are now uniq and only show once
-Centered notice message when there are no dishes in the meal
> UI Updates

- app/controllers/dishes_controller.rb
- app/controllers/foods_controller.rb
- app/controllers/sessions/dishes_controller.rb
- app/controllers/sessions/foods_controller.rb
- app/views/dishes/new.html.erb
- app/views/meals/new.html.erb
- config/routes.rb
- spec/features/users/user_can_edit_and_delete_dishes_in_meal_creation_spec.rb
- Users can delete dishes from a meal they are currently building
- Users can edit dishes they have in a meal they are currently building
> Dish edit delete

- app/models/user.rb
- app/views/help/show.html.erb
- app/views/results/index.html.erb
- spec/features/users/results_page_spec.rb
- spec/models/user_spec.rb
- Add further detail to the help page
- Add if/else logic to the results view page
- Add countdown on the results page that notifies user how many more gut feelings they need to add before results page will render charts
> Help Page and Results Page

- .travis.yml
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.css
- app/models/ingredient.rb
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/results/index.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/webpacker.yml
- spec/features/users/results_page_spec.rb
- spec/rails_helper.rb
- Add bar charts for user's best and worst ingredients(based on gut feelings) to results page
> Result charts

- app/controllers/results_controller.rb
- app/models/ingredient.rb
- app/views/results/index.html.erb
- spec/factories/ingredients.rb
- spec/features/results_spec.rb
- spec/features/users/can_add_previous_dishes_to_meals_spec.rb
- spec/models/ingredient_spec.rb
- spec/models/meal_spec.rb
Built table that displays a user's:
- Consumed ingredients
- The list of foods they're found in
- How many times they were eaten
- Their average gut feeling
> Food History Results Table

- Gemfile
- Gemfile.lock
> Add skylight gem to gemfile

- Gemfile.lock
- app/assets/stylesheets/application.css
- app/controllers/dishes_controller.rb
- app/controllers/foods_controller.rb
- app/controllers/sessions/dishes_controller.rb
- app/controllers/sessions/meals_controller.rb
- app/views/dishes/new.html.erb
- app/views/layouts/application.html.erb
- app/views/meals/new.html.erb
- app/views/results/index.html.erb
- app/views/users/show.html.erb
- Style table head rows
- Style navbar 
- Prevent user from adding the same food to a dish multiple times
- Prevent user from adding the same dish to a meal multiple times
> Refactors and styling

- app/assets/stylesheets/application.css
- app/views/dishes/new.html.erb
- app/views/meals/new.html.erb
- Add underline and light blue background
- Add top margin to select from previous table
> Style done adding boxes on new meal and dish pages

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/controllers/sessions_controller.rb
- app/models/user.rb
- app/views/dishes/new.html.erb
- app/views/layouts/application.html.erb
- app/views/meals/new.html.erb
- app/views/results/index.html.erb
- app/views/users/show.html.erb
- app/views/welcome/index.html.erb
- config/application.rb
- config/initializers/npm.rb
- config/routes.rb
- package-lock.json
- package.json
- spec/features/dashboard_spec.rb
- spec/features/help_page_spec.rb
- spec/features/results_spec.rb
- spec/features/users/google_oauth_spec.rb
- spec/features/users/user_adds_previous_foods_to_dishes_spec.rb
- Use npm to install morris.js06, a forked version that supports horizontal bar graphs
- Align morris js best and worst ingredient graphs side by side
- Align 'current' and 'select from previous' tables on new dish and new meal pages
- Add help information to home page, change link to redirect to that section
- Style headers using Roboto font
- Test coverage is still at 99.9%
> Align results graphs and tables side by side

- .travis.yml
- Use npm to install morris js v06 in Travis CI
> Edit Travis CI NPM Config

- .travis.yml
- Now npm install is global instead of local for morris.js06
> Update NPM Config for Travis CI

- app/assets/stylesheets/application.css
- app/views/partials/_meal_cart.html.erb
- Center sidebar content
- Remove underline from current meal title
- Add borders to main content and meal sidebar sections
- Reduce width of nested sidebar elements
- Test coverage is still at 99.9%
> Meal cart sidebar styling

- app/views/results/index.html.erb
- db/seeds.rb
- lib/tasks/create_most_ingredients.rake
Refactor seeds file to use defined ingredient processing methods and changeable structure
> Seed refactor
